/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient.js';
import AnimationDefinition from './model/AnimationDefinition.js';
import AnimationParameterDefinition from './model/AnimationParameterDefinition.js';
import ClientConfig from './model/ClientConfig.js';
import Color from './model/Color.js';
import InlineResponse200 from './model/InlineResponse200.js';
import Layer from './model/Layer.js';
import OneOfAnimationParameterDefinitionModelDefault from './model/OneOfAnimationParameterDefinitionModelDefault.js';
import ShaderDefinition from './model/ShaderDefinition.js';
import ShaderParameterDefinition from './model/ShaderParameterDefinition.js';
import AnimationsApi from './api/AnimationsApi.js';
import ClientsApi from './api/ClientsApi.js';
import ShadersApi from './api/ShadersApi.js';

/**
* API_for_managing_animations_shaders_and_client_configurations_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AnimationControlApi = require('index'); // See note below*.
* var xxxSvc = new AnimationControlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AnimationControlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AnimationControlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AnimationControlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AnimationDefinition model constructor.
     * @property {module:model/AnimationDefinition}
     */
    AnimationDefinition,

    /**
     * The AnimationParameterDefinition model constructor.
     * @property {module:model/AnimationParameterDefinition}
     */
    AnimationParameterDefinition,

    /**
     * The ClientConfig model constructor.
     * @property {module:model/ClientConfig}
     */
    ClientConfig,

    /**
     * The Color model constructor.
     * @property {module:model/Color}
     */
    Color,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The Layer model constructor.
     * @property {module:model/Layer}
     */
    Layer,

    /**
     * The OneOfAnimationParameterDefinitionModelDefault model constructor.
     * @property {module:model/OneOfAnimationParameterDefinitionModelDefault}
     */
    OneOfAnimationParameterDefinitionModelDefault,

    /**
     * The ShaderDefinition model constructor.
     * @property {module:model/ShaderDefinition}
     */
    ShaderDefinition,

    /**
     * The ShaderParameterDefinition model constructor.
     * @property {module:model/ShaderParameterDefinition}
     */
    ShaderParameterDefinition,

    /**
    * The AnimationsApi service constructor.
    * @property {module:api/AnimationsApi}
    */
    AnimationsApi,

    /**
    * The ClientsApi service constructor.
    * @property {module:api/ClientsApi}
    */
    ClientsApi,

    /**
    * The ShadersApi service constructor.
    * @property {module:api/ShadersApi}
    */
    ShadersApi
};
