/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The AnimationParameterDefinition model module.
 * @module model/AnimationParameterDefinition
 * @version 1.0.0
 */
export default class AnimationParameterDefinition {
  /**
   * Constructs a new <code>AnimationParameterDefinition</code>.
   * @alias module:model/AnimationParameterDefinition
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnimationParameterDefinition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnimationParameterDefinition} obj Optional instance to populate.
   * @return {module:model/AnimationParameterDefinition} The populated <code>AnimationParameterDefinition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnimationParameterDefinition();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('min'))
        obj.min = ApiClient.convertToType(data['min'], 'Number');
      if (data.hasOwnProperty('max'))
        obj.max = ApiClient.convertToType(data['max'], 'Number');
      if (data.hasOwnProperty('stepSize'))
        obj.stepSize = ApiClient.convertToType(data['stepSize'], 'Number');
      if (data.hasOwnProperty('default'))
        obj._default = ApiClient.convertToType(data['default'], Object);
      if (data.hasOwnProperty('columns'))
        obj.columns = ApiClient.convertToType(data['columns'], 'Number');
      if (data.hasOwnProperty('rows'))
        obj.rows = ApiClient.convertToType(data['rows'], 'Number');
      if (data.hasOwnProperty('enumElements'))
        obj.enumElements = ApiClient.convertToType(data['enumElements'], ['String']);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
AnimationParameterDefinition.TypeEnum = {
  /**
   * value: "bool"
   * @const
   */
  bool: "bool",

  /**
   * value: "slider"
   * @const
   */
  slider: "slider",

  /**
   * value: "string"
   * @const
   */
  _string: "string",

  /**
   * value: "textarea"
   * @const
   */
  textarea: "textarea",

  /**
   * value: "number"
   * @const
   */
  _number: "number",

  /**
   * value: "color"
   * @const
   */
  color: "color",

  /**
   * value: "enum"
   * @const
   */
  _enum: "enum"
};
/**
 * @member {module:model/AnimationParameterDefinition.TypeEnum} type
 */
AnimationParameterDefinition.prototype.type = undefined;

/**
 * @member {Number} min
 */
AnimationParameterDefinition.prototype.min = undefined;

/**
 * @member {Number} max
 */
AnimationParameterDefinition.prototype.max = undefined;

/**
 * @member {Number} stepSize
 */
AnimationParameterDefinition.prototype.stepSize = undefined;

/**
 * @member {Object} _default
 */
AnimationParameterDefinition.prototype._default = undefined;

/**
 * @member {Number} columns
 */
AnimationParameterDefinition.prototype.columns = undefined;

/**
 * @member {Number} rows
 */
AnimationParameterDefinition.prototype.rows = undefined;

/**
 * The index of the selected element should be used as the value in the setConfig endpoint
 * @member {Array.<String>} enumElements
 */
AnimationParameterDefinition.prototype.enumElements = undefined;

/**
 * @member {String} description
 */
AnimationParameterDefinition.prototype.description = undefined;

