/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';
import AnimationParameterDefinition from './AnimationParameterDefinition.js';

/**
 * The AnimationDefinition model module.
 * @module model/AnimationDefinition
 * @version 1.0.0
 */
export default class AnimationDefinition {
  /**
   * Constructs a new <code>AnimationDefinition</code>.
   * @alias module:model/AnimationDefinition
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnimationDefinition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnimationDefinition} obj Optional instance to populate.
   * @return {module:model/AnimationDefinition} The populated <code>AnimationDefinition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnimationDefinition();
      if (data.hasOwnProperty('animationName'))
        obj.animationName = ApiClient.convertToType(data['animationName'], 'String');
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], {'String': AnimationParameterDefinition});
    }
    return obj;
  }
}

/**
 * @member {String} animationName
 */
AnimationDefinition.prototype.animationName = undefined;

/**
 * @member {Object.<String, module:model/AnimationParameterDefinition>} parameters
 */
AnimationDefinition.prototype.parameters = undefined;

