/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';
import Layer from './Layer.js';

/**
 * The ClientConfig model module.
 * @module model/ClientConfig
 * @version 1.0.0
 */
export default class ClientConfig {
  /**
   * Constructs a new <code>ClientConfig</code>.
   * @alias module:model/ClientConfig
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClientConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientConfig} obj Optional instance to populate.
   * @return {module:model/ClientConfig} The populated <code>ClientConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientConfig();
      if (data.hasOwnProperty('layers'))
        obj.layers = ApiClient.convertToType(data['layers'], [Layer]);
      if (data.hasOwnProperty('dimmer'))
        obj.dimmer = ApiClient.convertToType(data['dimmer'], 'Number');
      if (data.hasOwnProperty('hueShift'))
        obj.hueShift = ApiClient.convertToType(data['hueShift'], 'Number');
      if (data.hasOwnProperty('rotate'))
        obj.rotate = ApiClient.convertToType(data['rotate'], 'Number');
      if (data.hasOwnProperty('pan'))
        obj.pan = ApiClient.convertToType(data['pan'], 'Number');
      if (data.hasOwnProperty('tilt'))
        obj.tilt = ApiClient.convertToType(data['tilt'], 'Number');
      if (data.hasOwnProperty('scale'))
        obj.scale = ApiClient.convertToType(data['scale'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Layer>} layers
 */
ClientConfig.prototype.layers = undefined;

/**
 * @member {Number} dimmer
 */
ClientConfig.prototype.dimmer = undefined;

/**
 * @member {Number} hueShift
 */
ClientConfig.prototype.hueShift = undefined;

/**
 * @member {Number} rotate
 */
ClientConfig.prototype.rotate = undefined;

/**
 * @member {Number} pan
 */
ClientConfig.prototype.pan = undefined;

/**
 * @member {Number} tilt
 */
ClientConfig.prototype.tilt = undefined;

/**
 * @member {Number} scale
 */
ClientConfig.prototype.scale = undefined;

