/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The Color model module.
 * @module model/Color
 * @version 1.0.0
 */
export default class Color extends Array {
  /**
   * Constructs a new <code>Color</code>.
   * @alias module:model/Color
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Color</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Color} obj Optional instance to populate.
   * @return {module:model/Color} The populated <code>Color</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Color();
      ApiClient.constructFromObject(data, obj, 'Number');
    }
    return obj;
  }
}
// Implement OneOfAnimationParameterDefinitionModelDefault interface:
