/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';
import ShaderParameterDefinition from './ShaderParameterDefinition.js';

/**
 * The ShaderDefinition model module.
 * @module model/ShaderDefinition
 * @version 1.0.0
 */
export default class ShaderDefinition {
  /**
   * Constructs a new <code>ShaderDefinition</code>.
   * @alias module:model/ShaderDefinition
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ShaderDefinition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShaderDefinition} obj Optional instance to populate.
   * @return {module:model/ShaderDefinition} The populated <code>ShaderDefinition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShaderDefinition();
      if (data.hasOwnProperty('shaderName'))
        obj.shaderName = ApiClient.convertToType(data['shaderName'], 'String');
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], {'String': ShaderParameterDefinition});
    }
    return obj;
  }
}

/**
 * @member {String} shaderName
 */
ShaderDefinition.prototype.shaderName = undefined;

/**
 * @member {Object.<String, module:model/ShaderParameterDefinition>} parameters
 */
ShaderDefinition.prototype.parameters = undefined;

