/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The ShaderParameterDefinition model module.
 * @module model/ShaderParameterDefinition
 * @version 1.0.0
 */
export default class ShaderParameterDefinition {
  /**
   * Constructs a new <code>ShaderParameterDefinition</code>.
   * @alias module:model/ShaderParameterDefinition
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ShaderParameterDefinition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShaderParameterDefinition} obj Optional instance to populate.
   * @return {module:model/ShaderParameterDefinition} The populated <code>ShaderParameterDefinition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShaderParameterDefinition();
      if (data.hasOwnProperty('min'))
        obj.min = ApiClient.convertToType(data['min'], 'Number');
      if (data.hasOwnProperty('max'))
        obj.max = ApiClient.convertToType(data['max'], 'Number');
      if (data.hasOwnProperty('stepSize'))
        obj.stepSize = ApiClient.convertToType(data['stepSize'], 'Number');
      if (data.hasOwnProperty('default'))
        obj._default = ApiClient.convertToType(data['default'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} min
 */
ShaderParameterDefinition.prototype.min = undefined;

/**
 * @member {Number} max
 */
ShaderParameterDefinition.prototype.max = undefined;

/**
 * @member {Number} stepSize
 */
ShaderParameterDefinition.prototype.stepSize = undefined;

/**
 * @member {Number} _default
 */
ShaderParameterDefinition.prototype._default = undefined;

/**
 * @member {String} description
 */
ShaderParameterDefinition.prototype.description = undefined;

