/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient.js";
import ShaderDefinition from '../model/ShaderDefinition.js';

/**
* Shaders service.
* @module api/ShadersApi
* @version 1.0.0
*/
export default class ShadersApi {

    /**
    * Constructs a new ShadersApi. 
    * @alias module:api/ShadersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiElementShaderGetShaderIDGet operation.
     * @callback moduleapi/ShadersApi~apiElementShaderGetShaderIDGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ShaderDefinition{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get details of a specific shader
     * @param {String} shaderID ID of the shader to retrieve
     * @param {module:api/ShadersApi~apiElementShaderGetShaderIDGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiElementShaderGetShaderIDGet(shaderID, callback) {
      
      let postBody = null;
      // verify the required parameter 'shaderID' is set
      if (shaderID === undefined || shaderID === null) {
        throw new Error("Missing the required parameter 'shaderID' when calling apiElementShaderGetShaderIDGet");
      }

      let pathParams = {
        'shaderID': shaderID
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ShaderDefinition;

      return this.apiClient.callApi(
        '/api/elementShader/get/{shaderID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiElementShaderImageShaderIDGet operation.
     * @callback moduleapi/ShadersApi~apiElementShaderImageShaderIDGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the image associated with a shader
     * @param {String} shaderID ID of the shader
     * @param {module:api/ShadersApi~apiElementShaderImageShaderIDGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiElementShaderImageShaderIDGet(shaderID, callback) {
      
      let postBody = null;
      // verify the required parameter 'shaderID' is set
      if (shaderID === undefined || shaderID === null) {
        throw new Error("Missing the required parameter 'shaderID' when calling apiElementShaderImageShaderIDGet");
      }

      let pathParams = {
        'shaderID': shaderID
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/elementShader/image/{shaderID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiElementShaderListGet operation.
     * @callback moduleapi/ShadersApi~apiElementShaderListGetCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, module:model/{'String': ShaderDefinition}>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all available shaders
     * @param {module:api/ShadersApi~apiElementShaderListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiElementShaderListGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = {'String': ShaderDefinition};

      return this.apiClient.callApi(
        '/api/elementShader/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiTextureShaderGetShaderIDGet operation.
     * @callback moduleapi/ShadersApi~apiTextureShaderGetShaderIDGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ShaderDefinition{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get details of a specific shader
     * @param {String} shaderID ID of the shader to retrieve
     * @param {module:api/ShadersApi~apiTextureShaderGetShaderIDGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiTextureShaderGetShaderIDGet(shaderID, callback) {
      
      let postBody = null;
      // verify the required parameter 'shaderID' is set
      if (shaderID === undefined || shaderID === null) {
        throw new Error("Missing the required parameter 'shaderID' when calling apiTextureShaderGetShaderIDGet");
      }

      let pathParams = {
        'shaderID': shaderID
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ShaderDefinition;

      return this.apiClient.callApi(
        '/api/textureShader/get/{shaderID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiTextureShaderImageShaderIDGet operation.
     * @callback moduleapi/ShadersApi~apiTextureShaderImageShaderIDGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the image associated with a shader
     * @param {String} shaderID ID of the shader
     * @param {module:api/ShadersApi~apiTextureShaderImageShaderIDGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiTextureShaderImageShaderIDGet(shaderID, callback) {
      
      let postBody = null;
      // verify the required parameter 'shaderID' is set
      if (shaderID === undefined || shaderID === null) {
        throw new Error("Missing the required parameter 'shaderID' when calling apiTextureShaderImageShaderIDGet");
      }

      let pathParams = {
        'shaderID': shaderID
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/textureShader/image/{shaderID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiTextureShaderListGet operation.
     * @callback moduleapi/ShadersApi~apiTextureShaderListGetCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, module:model/{'String': ShaderDefinition}>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all available shaders
     * @param {module:api/ShadersApi~apiTextureShaderListGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiTextureShaderListGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = {'String': ShaderDefinition};

      return this.apiClient.callApi(
        '/api/textureShader/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}