/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AnimationControlApi);
  }
}(this, function(expect, AnimationControlApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AnimationDefinition', function() {
      beforeEach(function() {
        instance = new AnimationControlApi.AnimationDefinition();
      });

      it('should create an instance of AnimationDefinition', function() {
        // TODO: update the code to test AnimationDefinition
        expect(instance).to.be.a(AnimationControlApi.AnimationDefinition);
      });

      it('should have the property animationName (base name: "animationName")', function() {
        // TODO: update the code to test the property animationName
        expect(instance).to.have.property('animationName');
        // expect(instance.animationName).to.be(expectedValueLiteral);
      });

      it('should have the property parameters (base name: "parameters")', function() {
        // TODO: update the code to test the property parameters
        expect(instance).to.have.property('parameters');
        // expect(instance.parameters).to.be(expectedValueLiteral);
      });

    });
  });

}));
