/*
 * Animation Control API
 * API for managing animations, shaders, and client configurations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AnimationControlApi);
  }
}(this, function(expect, AnimationControlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AnimationControlApi.ShadersApi();
  });

  describe('(package)', function() {
    describe('ShadersApi', function() {
      describe('apiElementShaderGetShaderIDGet', function() {
        it('should call apiElementShaderGetShaderIDGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiElementShaderGetShaderIDGet call and complete the assertions
          /*

          instance.apiElementShaderGetShaderIDGet(shaderID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AnimationControlApi.ShaderDefinition);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiElementShaderImageShaderIDGet', function() {
        it('should call apiElementShaderImageShaderIDGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiElementShaderImageShaderIDGet call
          /*

          instance.apiElementShaderImageShaderIDGet(shaderID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiElementShaderListGet', function() {
        it('should call apiElementShaderListGet successfully', function(done) {
          // TODO: uncomment apiElementShaderListGet call and complete the assertions
          /*

          instance.apiElementShaderListGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Object);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(AnimationControlApi.ShaderDefinition);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiTextureShaderGetShaderIDGet', function() {
        it('should call apiTextureShaderGetShaderIDGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiTextureShaderGetShaderIDGet call and complete the assertions
          /*

          instance.apiTextureShaderGetShaderIDGet(shaderID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AnimationControlApi.ShaderDefinition);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiTextureShaderImageShaderIDGet', function() {
        it('should call apiTextureShaderImageShaderIDGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiTextureShaderImageShaderIDGet call
          /*

          instance.apiTextureShaderImageShaderIDGet(shaderID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiTextureShaderListGet', function() {
        it('should call apiTextureShaderListGet successfully', function(done) {
          // TODO: uncomment apiTextureShaderListGet call and complete the assertions
          /*

          instance.apiTextureShaderListGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Object);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(AnimationControlApi.ShaderDefinition);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
